core_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('api/', include('klin_api.urls')),
    path('change_password', auth_views.PasswordChangeView.as_view(template_name= 'password/password_change.html'),
         name='password_change'),
    path('change_password/done', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'),
         name='password_change_done'),

    path('password_reset', auth_views.PasswordResetView.as_view(template_name= 'password/password_reset.html',
         subject_template_name='password/password_reset_subject.txt',
                                                                email_template_name='password/password_reset_email.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activation_sent/', views.activation_sent_view, name="activation_sent"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

klin_api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView

app_name = 'klin_api'

urlpatterns = [
    path('', include('djoser.urls')),
    path('', include('djoser.urls.authtoken')),
    path('create-user/', views.UserCreate.as_view(), name='account-create'),
    path('create-agency/', views.AgencyCreate.as_view(), name='agent-create'),
    path('profile/', views.ProfileView.as_view(), name='view-profile'),
    path('update-profile/', views.ProfileUpdateView.as_view(), name='update-profile'),
    path('update-user/', views.UserUpdateView.as_view(), name='update-user'),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='klin_api:schema'), name='docs')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.landing, name='landing'),
    path('home/', views.home, name='home'),
    path('login-user/', views.login_request, name='login-user'),
    path('login-agency/', views.login_agency, name='login_agency'),
    path('signup/user/', views.signup_user, name='signup_user'),
    path('signup/agency/', views.signup_agency, name='signup_agency'),
    path('logout/', views.logout_request, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('blog/', views.BlogListView.as_view(), name='blog'),
    path('about/', views.about, name='about'),
    path('recycle-pickup/', views.recycle_pickup, name= 'recycle-pickup'),
    path('recycle-dropoff/', views.recycle_drop_off, name= 'recycle-dropoff'),
    path('recycle-delivery/', views.recycle_delivery_agency, name= 'recycle-delivery'),
    path('recycle-location/', views.recycle_location_agency, name= 'recycle-location'),
    path('login/', views.sign_up_as, name='login'),
    path('collect/', views.collect, name='collect'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KlinLag/main_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from klin_api.models import User
from django.contrib.gis.db import models

# Create your models here.


class SectionPoints(models.Model):
    appUser = models.ForeignKey(User, on_delete=models.CASCADE)
    pointsGained = models.IntegerField

    def __str__(self):
        return 'points'

main_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from klin_api.models import User
from autoslug import AutoSlugField
import datetime
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class Schedule(models.Model):
    title = models.CharField(max_length=200)
    start_time = models.DateTimeField(default=datetime.date.today)

    def __str__(self):
        return self.title
    @property
    def get_calendar_url(self):
        url = reverse('schedule_edit', args=(self.id,))
        return f'<p>{self.title}</p><a href="{url}">edit</a>'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    section_points = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user.first_name)


class Blogpost(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    image = models.ImageField(default='default.png', upload_to='blog_pics')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])


class Comment(models.Model):
    post = models.ForeignKey(Blogpost,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Waste(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class PickupTime(models.Model):
    time_range = models.CharField(max_length=50)

    def __str__(self):
        return self.time_range


class PickupRequest(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = PhoneNumberField(null=False, blank=False)
    address = models.CharField(max_length=300)
    date = models.DateField(auto_now_add=False)
    time = models.ForeignKey(PickupTime, on_delete=models.CASCADE)
    waste_type = models.ManyToManyField(Waste)
    quantity = models.IntegerField()
    extra_note = models.TextField(max_length=500)
    is_donor = models.BooleanField(default=False)
    is_collector = models.BooleanField(default=False)

    def __str__(self):
        return self.full_name

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from .models import User, Profile
from django.db import IntegrityError
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from rest_framework.reverse import reverse_lazy
from django.views.generic.list import ListView
from .utils import Calendar
from .models import Schedule, Blogpost
from .decorators import user_is_collector, user_is_giver
from django.forms import EmailField


def activation_sent_view(request):
    return render(request, 'activation_sent.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.signup_confirmation = True
        user.save()
        messages.success(request, 'Your account has been activated')
        if user.is_giver:
            return redirect('main_app:login-user')
        if user.is_collector:
            return redirect('main_app:login_agency')
    else:
        return render(request, 'activation_invalid.html')


def signup_user(request):
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=raw_password)
            user.is_active = False
            user.save()
            Profile.objects.create(user=user)
            current_site = get_current_site(request)
            subject = 'Please Activate Your Account'
            message = render_to_string('activation_request.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('activation_sent')
    else:
        form = UserSignUpForm
    return render(request, 'usersignup.html', {'signup_user_form': form})


def signup_agency(request):
    if request.method == 'POST':
        form = AgencySignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=raw_password)
            user.is_active = False
            user.save()
            Profile.objects.create(user=user)
            current_site = get_current_site(request)
            subject = 'Please Activate Your Account'
            message = render_to_string('activation_request.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('activation_sent')
    else:
        form = AgencySignUpForm
    return render(request, 'companysignup.html', {'signup_agency_form': form})


def login_request(request):
    current_user = request.user
    # if current_user.is_authenticated:
    #     return redirect('main_app:home')
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_giver:
                    login(request, user)
                    messages.info(request, f'You are now logged in as {username}')
                    return redirect('main_app:home')
                else:
                    messages.error(request, "Your account is a collector's account, Sign in on the collectors page")
                    return redirect('main_app:index')
            else:
                messages.error(request, 'Invalid username or password')

        else:
            messages.error(request, 'Account has not been activated or details have not been entered correctly.')
    form = UserLoginForm
    return render(request=request, template_name='usersignin.html', context={'login_form': form, 'user': current_user})


def login_agency(request):
    current_user = request.user
    # if current_user.is_authenticated:
    #     return redirect('main_app:home')
    if request.method == 'POST':
        form = AgencyLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_collector:
                    login(request, user)
                    messages.info(request, f'You are now logged in as {username}')
                    return redirect('main_app:collect')
                else:
                    messages.error(request, "Your account is a donor's account, Sign in on the donors page")
                    return redirect('main_app:index')
            else:
                messages.error(request, 'Invalid username or password')
        else:
            messages.error(request, 'Account has not been activated or details have not been entered correctly.')
    form = UserLoginForm
    return render(request=request, template_name='companysignin.html', context={'login_form': form, 'user':current_user})


@login_required
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("main_app:index")

@login_required
def home(request):
    user = User.objects.get(id=request.user.id)

    return render(request, 'home.html', {'user': user})


def landing(request):
    user = User.objects.get(id=request.user.id)

    return render(request, 'baseauth.html', {'user':user})


def sign_up_as(request):
    user = User.objects.get(id=request.user.id)
    if user.is_authenticated:
        return redirect('main_app:home')
    return render(request, 'signinas.html')


def index(request):
    user = request.user
    return render(request, 'index.html', {'user':user})

@user_is_giver
@login_required
def my_profile(request):
    p = request.user.profile
    user = p.user
    return render(request, 'my_profile.html', {'profile':p, 'user':user})

@user_is_giver
@login_required
def edit_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('main_app:my_profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context ={
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'edit_profile.html', context)


class CalendarView(ListView):
    model = Schedule
    template_name = 'calendar.html'
    success_url = reverse_lazy("calendar")

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     date = get_date(self.request.GET.get('month', None))
    #     cal = Calendar(date.year, date.month)
    #     html_cal = calendar.formatmonth(withyear=True)
    #     context['calendar'] = mark_safe(html_cal)
    #     context[prev_month] = prev_month(date)
    #     context[next_month] = next_month(date)
    #
    #     return context


class BlogListView(ListView):
    model = Blogpost
    template_name = 'blog-post2.html'


def post_detail(request, pk):
    post = get_object_or_404(Blogpost, pk =pk)
    user = request.user
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.post = post
            data.author = user
            data.save()
            return redirect('main_app:post_detail', pk = pk)
    else:
        form = NewCommentForm
    return render(request, 'blogpost1.html', {'post': post, 'comment_form':form})


def about(request):
    return render(request, 'About.html')


@user_is_giver
@login_required
def recycle_pickup(request):
    if request.method == 'POST':
        form = NewRequestFormDonor(request.POST)
        if form.is_valid():
            waste = form.cleaned_data.get('waste_type')
            form.waste_type = waste
            form.save()
            messages.success(request, 'Your request has been received, you will be contacted shortly')
            return redirect('main_app:recycle-pickup')

    else:
        form = NewRequestFormDonor
    return render(request, 'recyclable-pickup.html', {'request_form': form})


@user_is_collector
@login_required
def recycle_delivery_agency(request):
    if request.method == 'POST':

main_app/templates/baseauth.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <!-- font awesome -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <!-- font -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700;900&display=swap" rel="stylesheet">

{% block title %}
{% endblock %}
</head>

<body>
{% include 'messages.html' %}
  <nav class="navbar navbar-expand-lg navbar-light header__navigation">
    <div class="container">
      <a class="navbar-brand" href="#">
        <img src="../../static/assets/logo.svg" alt="klinglag logo" width="100">
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav main-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main_app:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:about' %}">About Us</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:blog' %}">Blog</a>
          </li>
            {% if user.is_authenticated %}
                {% if user.is_giver %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:home' %}">Dashboard</a>
          </li>
                    {% elif user.is_collector %}
                    <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:collect' %}">Dashboard</a>
          </li>
                    {% endif %}
                <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:logout' %}">Logout</a>
          </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    {% block card %}
        {% block body %}
        {% endblock %}
{% endblock %}
<footer class="footer py-7 mt-10">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-12">
          <img src="../../static/assets/logo-white.svg" alt="footer logo" width="160" class="footer-logo">
          <div class="newsletter">
            <p class="newsletter-title">subscribe to our newsletter</p>
            <form class="d-flex align-items-center">
              <input type="email" class="form-control" placeholder="enter your email address">
              <button type="submit" class="btn btn-subscribe">Subscribe</button>
            </form>
          </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12">
          <h3 class="heading-footer text-white">About Us</h3>
          <nav class="nav flex-column footer-nav">
            <a class="nav-link" href="#">Who we are</a>
            <a class="nav-link" href="#">Our Mission</a>
            <a class="nav-link" href="#">Services</a>
            <a class="nav-link" href="#">Partners</a>
          </nav>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12">
          <h3 class="heading-footer text-white">Resources</h3>
          <nav class="nav flex-column footer-nav">
            <a class="nav-link" href="#">Careers</a>
            <a class="nav-link" href="#">Blog</a>
            <a class="nav-link" href="#">Volunteers</a>
            <a class="nav-link" href="#">FAQs</a>
          </nav>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12">
          <h3 class="heading-footer text-white">Contact Us</h3>
          <nav class="nav flex-column footer-nav">
            <div class="d-flex align-items-center mb-2 text-white">
              <i class="fa fa-home fa-3x"></i>
              <a class="nav-link" href="#">8 Jubliee-CMD Road, Magodo, Lagos State</a>
            </div>
            <div class="d-flex align-items-center mb-2 text-white">
              <i class="fa fa-phone fa-3x"></i>
              <a class="nav-link" href="#">+2349000099900</a>
            </div>
            <div class="d-flex align-items-center mb-2 text-white">
              <i class="fa fa-envelope fa-3x"></i>
              <a class="nav-link" href="#">hello@klinlag.ng</a>
            </div>
          </nav>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <h4 class="connect text-center text-white"><span>Connect with us</span></h4>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-lg-4 col-md-4 col-sm-12">
          <ul class="nav footer-nav-left">
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Terms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Privacy</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
          <ul class="nav footer-nav-secondary justify-content-center">
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fa fa-facebook fa-2x text-white" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fa fa-twitter fa-2x text-white" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fa fa-instagram fa-2x text-white" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fa fa-whatsapp fa-2x text-white" aria-hidden="true"></i></a>
            </li>
          </ul>
        </div>
        <div class="col-4">

        </div>
      </div>
    </div>
  </footer>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    crossorigin="anonymous"></script>
</body>

</html>

main_app/templates/calendar.html
{% extends 'baseauth.html' %}
{% load static %}
{% block title %}

{#    <link rel="stylesheet" media="all" href={% static "vendor/select2/select2.min.css"%} >#}
{#    <link rel="stylesheet" media="all" href={% static "vendor/datepicker/daterangepicker.css"%} >#}
    <link rel="stylesheet" href="../../../static/styles/usersignup.css">
    <!-- Main CSS-->
    <link rel="stylesheet" media="all" href={% static "css/main.css"%} >
    <title>Klin Lag</title>

{% endblock %}
{% block content %}

<a href="{% url 'calendar' %}?{{ prev_month }}">Previous Month</a><a href="{% url 'calendar' %}?{{ next_month }}">Next Month</a>

{{ calendar }}

{% endblock %}

main_app/templates/home.html
{% extends 'baseauth.html' %}
{% load static %}
{% block title %}
{#    <link rel="stylesheet" media="all" href={% static "vendor/select2/select2.min.css"%} >#}
{#    <link rel="stylesheet" media="all" href={% static "vendor/datepicker/daterangepicker.css"%} >#}
    <link rel="stylesheet" href="../../static/styles/usersignup.css">
    <!-- Main CSS-->
    <link rel="stylesheet" media="all" href={% static "css/main.css"%} >
    <title>Klin Lag</title>
{% endblock %}
{% block card %}
    <div class="p-t-180 p-b-100 font-lato">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
{% block body %}
    {% load crispy_forms_tags %}
    <h2 class="title">Welcome</h2>


    {% if user.is_giver %}
        <a href="{% url 'main_app:my_profile' %}"><button class="btn btn--green">My Profile</button></a>
    <br/><br/>
    <a href="{% url 'main_app:recycle-dropoff' %}"><button class="btn btn--green">Recycle DropOff</button></a>
              <br/><br/>
    <a href="{% url 'main_app:recycle-pickup' %}"><button class="btn btn--green">Recycle PickUp</button></a>
    <br/><br/>

        {% elif user.is_collector %}
        <a href="{% url 'main_app:recycle-location' %}"><button class="btn btn--green">PickUp Locations</button></a>
              <br/><br/>
    <a href="{% url 'main_app:recycle-delivery' %}"><button class="btn btn--green">Request Recyclable Delivery</button></a>
    <br/><br/>
    {% endif %}
                    <a href="{% url 'main_app:logout' %}"><button class="btn btn-secondary">Logout</button></a>
{% endblock %}
                 </div>
            </div>
        </div>
    </div>
{% endblock %}

main_app/templates/navbarfooter.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- FontAwesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700&display=swap" rel="stylesheet">
  <!-- Styling -->
    <link href="../../static/styles/sign-in.css" rel="stylesheet" >
  <link rel="stylesheet" href="../../static/styles/navbarfooter.css">

    {% block title %}
    {% endblock %}

</head>
<body>
  <nav class="navbar">
    <div class="nav-item">
      <div class="left">
        <img src="../../static/assets/logo.png" alt="LOGO">
      </div>
      <div class="right">
        <div class="nav-links">
          <a href="{% url 'main_app:index' %}">HOME</a>
          <a href="{% url 'main_app:about' %}">ABOUT US</a>
          <a href="/">HOW IT WORKS</a>
          <a href="/">CONTACT US</a>
          <a href="{% url 'main_app:blog'%}">BLOG</a>
        </div>
      </div>
    </div>
  </nav>
{% block content %}
  {% endblock %}
  <footer class="footer">
    <div class="btm-content">
      <div class="item">
        <div class="btm-logo">
          <img src="../../static/assets/logo-white.png" alt="btm-logo">
        </div>
        <div class="input-area">
          <p class="input-text">SUBSCRIBE TO OUR NEWSLETTER</p>
          <input type="email" name="email" id="email" placeholder="Enter your email address">
          <button class="btn">SUBSCRIBE</button>
        </div>
      </div>
      <div class="item">
        <h4 class="text-lead">ABOUT US</h4>
        <p class="text">Who we are</p>
        <p class="text">Our Mission</p>
        <p class="text">Services</p>
        <p class="text">Our Projects</p>
        <p class="text">Partnerships</p>
      </div>
      <div class="item">
        <h4 class="text-lead">RESOURCES</h4>
        <p class="text">Careers</p>
        <p class="text">Blogs</p>
        <p class="text">My Points</p>
        <p class="text">Gallery</p>
        <p class="text">FAQs</p>
      </div>
      <div class="item">
        <h4 class="text-lead contact">CONTACT US</h4>
        <p class="text icons">
          <i class="fas fa-home">
          </i>
          8 Jubliee-CMD Road,<br> 
          Magodo, Lagos State
        </p>
        <p class="text icons">
          <i class="fas fa-phone-alt"></i>+2349000099900
        </p>
        <p class="text icons">
          <i class="fas fa-envelope"></i>hello@klinlag.ng
        </p>
      </div>
    </div>
    <div class="connect">
      <div class="line">
        <img src="../../static/assets/line.png" alt="line">
      </div>
      <h4 class="connect-text">CONNECT WITH US</h4>
      <div class="line">
        <img src="../../static/assets/line.png" alt="line">
      </div>
    </div>
    <div class="connect-icons">
      <div class="left">
        <a href="#" class="text">Terms</a>
        <a href="#" class="text">Privacy</a>
      </div>
      <div class="icons-connect">
        <a href="facebook.com"><i class="fab fa-facebook-f"></i></a>
        <a href="twitter.com"><i class="fab fa-twitter"></i></a>
        <a href="instagram.com"><i class="fab fa-instagram"></i></a>
        <a href="youtube.com"><i class="fab fa-youtube"></i></a>
      </div>
    </div>
  </footer>
</body>
</html>